#!/bin/zsh
#autoload
# Delete partitions during install process
# Authors:
#   JB
#

## Delete previous partitions if exist
function partition_delete {
    wipefs -a $1
    ## Clean partion table
    sgdisk $1 -Zo
}
partition_delete "$@"
