#!/bin/zsh
#autoload
# Set pacman options beforepacstrap process
# Authors:
#   JB
#
function prepare_pacman {
    sed -i 's/^#Color/Color/g' /etc/pacman.conf
    sed -i 's/^#TotalDownload/TotalDownload/g' /etc/pacman.conf
    sed -i 's/^#VerbosePkgLists/VerbosePkgLists/g' /etc/pacman.conf

    # if (( # == 0 )); then
        printf "$fg[yellow]Read Package list: $1$reset_color\n\n"

        while read -r line
            do pck+="$line "
        done < $1

        printf "$fg[yellow]Extra packages to instal:\n $pck $reset_color\n\n"
    # fi

}
prepare_pacman "$@"
